#pragma checksum "..\..\AddProjectWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "D1C25D3206AA1456EADC04ED0A5D54B001214899"
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using AppProjects;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace AppProjects {
    
    
    /// <summary>
    /// DlgProject
    /// </summary>
    public partial class DlgProject : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 15 "..\..\AddProjectWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grid1;
        
        #line default
        #line hidden
        
        
        #line 30 "..\..\AddProjectWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox BoxCategory;
        
        #line default
        #line hidden
        
        
        #line 31 "..\..\AddProjectWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonAddCategory;
        
        #line default
        #line hidden
        
        
        #line 37 "..\..\AddProjectWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox BoxCompany;
        
        #line default
        #line hidden
        
        
        #line 40 "..\..\AddProjectWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonAddCategory_Copy;
        
        #line default
        #line hidden
        
        
        #line 56 "..\..\AddProjectWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox BoxOwner;
        
        #line default
        #line hidden
        
        
        #line 57 "..\..\AddProjectWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonAddCategory_Copy1;
        
        #line default
        #line hidden
        
        
        #line 62 "..\..\AddProjectWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonNew;
        
        #line default
        #line hidden
        
        
        #line 63 "..\..\AddProjectWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ButtonCancel;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Projects;component/addprojectwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\AddProjectWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 8 "..\..\AddProjectWindow.xaml"
            ((AppProjects.DlgProject)(target)).Loaded += new System.Windows.RoutedEventHandler(this.Window_Loaded);
            
            #line default
            #line hidden
            return;
            case 2:
            this.grid1 = ((System.Windows.Controls.Grid)(target));
            return;
            case 3:
            this.BoxCategory = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 4:
            this.ButtonAddCategory = ((System.Windows.Controls.Button)(target));
            
            #line 31 "..\..\AddProjectWindow.xaml"
            this.ButtonAddCategory.Click += new System.Windows.RoutedEventHandler(this.ButtonAddCategory_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.BoxCompany = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 6:
            this.ButtonAddCategory_Copy = ((System.Windows.Controls.Button)(target));
            
            #line 40 "..\..\AddProjectWindow.xaml"
            this.ButtonAddCategory_Copy.Click += new System.Windows.RoutedEventHandler(this.ButtonAddCompany_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            this.BoxOwner = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 8:
            this.ButtonAddCategory_Copy1 = ((System.Windows.Controls.Button)(target));
            
            #line 57 "..\..\AddProjectWindow.xaml"
            this.ButtonAddCategory_Copy1.Click += new System.Windows.RoutedEventHandler(this.ButtonAddOwner_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            this.ButtonNew = ((System.Windows.Controls.Button)(target));
            
            #line 62 "..\..\AddProjectWindow.xaml"
            this.ButtonNew.Click += new System.Windows.RoutedEventHandler(this.ButtonNew_Click);
            
            #line default
            #line hidden
            return;
            case 10:
            this.ButtonCancel = ((System.Windows.Controls.Button)(target));
            
            #line 63 "..\..\AddProjectWindow.xaml"
            this.ButtonCancel.Click += new System.Windows.RoutedEventHandler(this.ButtonCancel_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

