//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppProjects
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectDB : DbContext
    {
        public ProjectDB()
            : base("name=ProjectDBs")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Comments> Comments { get; set; }
        public virtual DbSet<Companies> Companies { get; set; }
        public virtual DbSet<Lists> Lists { get; set; }
        public virtual DbSet<Persons> Persons { get; set; }
        public virtual DbSet<Projects> Projects { get; set; }
        public virtual DbSet<Recipients> Recipients { get; set; }
        public virtual DbSet<Tasks> Tasks { get; set; }
        public virtual DbSet<Executers> Executers { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<ViewObject> ViewObject { get; set; }
    }
}
