//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppProjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipients
    {
        public int Id { get; set; }
        public int Id_Person { get; set; }
        public int Id_Comment { get; set; }
        public string Status { get; set; }
        public Nullable<int> Id_Owner { get; set; }
    }
}
