//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppProjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewObject
    {
        public Nullable<int> Id_Owner { get; set; }
        public int Id_Company { get; set; }
        public Nullable<int> Id_Project { get; set; }
        public Nullable<int> Id_List { get; set; }
        public Nullable<int> Id_Task { get; set; }
        public Nullable<int> Id_Comment { get; set; }
    }
}
